minimumReleaseAge: 10080 # 1 week

publicHoistPattern:
  - "@typescript/*"
  - "@nitrogql/*"

packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAgeExclude:
  # Renovate security update: valibot@1.4.2
  - valibot@1.4.2
