minimumReleaseAge: 10080 # 1 week

publicHoistPattern:
  - "@typescript/*"
  - "@nitrogql/*"

packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAgeExclude:
  # Renovate security update: vite@7.3.5
  - vite@7.3.5
