minimumReleaseAge: 10080 # 1 week

publicHoistPattern:
  - "@typescript/*"
  - "@nitrogql/*"

packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAgeExclude:
  # Renovate security update: storybook@10.2.10
  - storybook@10.2.10
