
on:
  pull_request:
    branches: [ main ]
    paths: [ apps/server/** ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-schema:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }

      # cspell:ignore Swatinem
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - run: cargo run --bin schema-gen
        working-directory: apps/server

      - run: git diff --exit-code
